# .cirrus.yml

# 定义一个任务
task:
  build:
    script:
      - echo "Building kernel"

# 定义一个工作流程
workflow:
  kernel-build:
    # 设置触发条件为手动触发
    on:
      workflow_dispatch:

    # 定义工作流程中的步骤
    steps:
      - name: Checkout code
        run: git checkout $CIRRUS_BRANCH

      - name: Build kernel
        run: make kernel

      - name: Run specific workflows
        run: |
          # 运行特定的 YAML 文件
          cirrus run .github/workflows/build_lmi\ \(Project\ Elixir\).yml
          cirrus run .github/workflows/build_lmi.yml
          cirrus run .github/workflows/build_xc.yml
          cirrus run .github/workflows/build_xzp.yml
