name: Build Kernel (lmi)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: |
          echo "KERNEL_SOURCE=$(cat config.env | grep -w "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep -w "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "KERNEL_TARGET=$(cat config.env | grep -w "KERNEL_TARGET" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "BUILD_ARGS=$(cat config.env | grep -w "BUILD_ARGS" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
          echo "SOURCE_BOOT_IMAGE=$(cat config.env | grep -w "SOURCE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y-%m-%d-%H-%M")" >> $GITHUB_ENV
          sudo apt-get update
          sudo -E apt-get -qq install -y bc bison build-essential ccache curl flex git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev x11proto-core-dev libx11-dev libgl1-mesa-dev unzip fontconfig make python2
          sudo -E apt-get -qq install libfuse-dev
          mkdir -p $GITHUB_WORKSPACE/kernel_buildspace
          
      - name: Pull toolchain
        run: |
          cd $GITHUB_WORKSPACE/kernel_buildspace
          mkdir clang && cd clang
          wget https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-19.1.5-release/WeebX-Clang-19.1.5.tar.gz
          tar zxvf WeebX-Clang-19.1.5.tar.gz
          
      - name: Pull kernel source
        run: |
          cd $GITHUB_WORKSPACE/kernel_buildspace
          git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source

      - name: Setup KernelSU
        run: |
          cd $GITHUB_WORKSPACE/kernel_buildspace/kernel-source
          rm -rf KernelSU
          rm -rf drivers/kernelsu
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_buildspace/kernel-source
          export CLANG_PATH=$GITHUB_WORKSPACE/kernel_buildspace/clang
          export PATH=${CLANG_PATH}/bin:${PATH}
          args="                  ARCH=arm64 \
                                  CC=clang \
                                  O=out \
                                  ${{ env.BUILD_ARGS }} \
                                  CROSS_COMPILE=aarch64-linux-gnu- \
                                  CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                                  CLANG_TRIPLE=aarch64-linux-gnu- "
          make ${args} ${{ env.KERNEL_TARGET }}
          make -j$(nproc --all) ${args}

      - name: Download source boot image and magiskboot
        run: |
          cd $GITHUB_WORKSPACE/kernel_buildspace/kernel-source/out/arch/arm64/boot
          wget https://github.com/dibin666/toolchains/releases/download/magiskboot/magiskbootx86_64
          chmod +x magiskbootx86_64
          wget -O boot.img ${{ env.SOURCE_BOOT_IMAGE }}

      - name: Replace source-boot kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_buildspace/kernel-source/out/arch/arm64/boot
          ./magiskbootx86_64 unpack boot.img
          mv -f Image kernel
          ./magiskbootx86_64 repack boot.img
          ls

      - name: Upload boot image
        uses: actions/upload-artifact@v4
        with:
          name: boot-${{ env.BUILD_TIME }}
          path: kernel_buildspace/kernel-source/out/arch/arm64/boot/new-boot.img


